# Generated by Django 5.1.11 on 2025-07-05 06:27

import ckeditor.fields
import common.utils
import common.validators
import django.core.validators
import django.utils.timezone
import events.models.base
import events.models.discipline
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('format_type', models.CharField(choices=[('video_url', 'Видео'), ('image', 'Изображение')], help_text='Выберите тип медиа (Изображение или видео)', max_length=25, verbose_name='Тип контента')),
                ('video_url', models.CharField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', max_length=1000, null=True, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('card_image', models.ImageField(help_text='Загрузите изображение для карточки(страница мероприятий)', max_length=1000, upload_to=events.models.base.BaseEvent.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('yandex_address', models.CharField(help_text='Введите iframe Яндекс.Карт, начинающийся с <iframe>.', max_length=1000, validators=[common.validators.validate_iframe], verbose_name='Адрес Яндекс.Карт')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип площадки',
                'verbose_name_plural': 'Типы площадок',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название дисциплины')),
                ('first_image', models.ImageField(help_text='Вытянутое изображение (страница направление - первый блок)', max_length=1000, upload_to=events.models.discipline.Discipline.setup_first_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('second_image', models.ImageField(help_text='Изображение для страницы направления (2 блок и так далее)', max_length=1000, upload_to=events.models.discipline.Discipline.setup_second_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('description', models.TextField(help_text='Блок (страница направления)', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дисциплина уличной культуры',
                'verbose_name_plural': 'Дисциплины уличных культур',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('format_type', models.CharField(choices=[('video_url', 'Видео'), ('image', 'Изображение')], help_text='Выберите тип медиа (Изображение или видео)', max_length=25, verbose_name='Тип контента')),
                ('video_url', models.CharField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', max_length=1000, null=True, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('card_image', models.ImageField(help_text='Загрузите изображение для карточки(страница мероприятий)', max_length=1000, upload_to=events.models.base.BaseEvent.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('yandex_address', models.CharField(help_text='Введите iframe Яндекс.Карт, начинающийся с <iframe>.', max_length=1000, validators=[common.validators.validate_iframe], verbose_name='Адрес Яндекс.Карт')),
                ('is_our_project', models.BooleanField(default=False, help_text='Организовано нашей платформой', verbose_name='Наш проект')),
                ('is_priority', models.BooleanField(default=False, help_text='Отображается в топе мероприятий', verbose_name='Приоритетное мероприятие')),
                ('service_id', models.CharField(help_text='Идентификатор для интеграции с внешними системами', max_length=255, verbose_name='ID, SLUG внешнего сервиса')),
                ('starting_date', models.DateTimeField(verbose_name='Дата начала')),
                ('ending_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventActivityType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='GallerySubDiscipline',
            fields=[
                ('format_type', models.CharField(choices=[('video_url', 'Видео'), ('image', 'Изображение')], help_text='Выберите тип медиа (Изображение или видео)', max_length=25, verbose_name='Тип контента')),
                ('video_url', models.CharField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', max_length=1000, null=True, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, help_text='Использовать как основное изображение для заставки', verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Элементы галереи',
            },
        ),
        migrations.CreateModel(
            name='SubDiscipline',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название подкатегории')),
                ('description', ckeditor.fields.RichTextField(help_text='Подробное описание с возможностью форматирования', verbose_name='Полное описание')),
                ('image', models.ImageField(help_text='Загрузите изображение для главной страницы (отображение направлений)', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('main_page_info', models.TextField(help_text='Текст для карточки на главной странице', verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Подкатегория дисциплины',
                'verbose_name_plural': 'Подкатегории дисциплин',
            },
        ),
    ]
