# Generated by Django 5.1.11 on 2025-07-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='area',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.areatype', verbose_name='Тип площадки'),
        ),
        migrations.AddField(
            model_name='area',
            name='discipline',
            field=models.ForeignKey(help_text='Выберите дисциплину уличного спорта', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_discipline', to='events.discipline', verbose_name='Дисциплина уличного спорта'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='event',
            name='discipline',
            field=models.ForeignKey(help_text='Выберите дисциплину уличного спорта', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_discipline', to='events.discipline', verbose_name='Дисциплина уличного спорта'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventactivitytype', verbose_name='Тип мероприятия'),
        ),
        migrations.AddField(
            model_name='subdiscipline',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_disciplines', to='events.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='gallerysubdiscipline',
            name='subdiscipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='events.subdiscipline', verbose_name='Поддисциплина'),
        ),
        migrations.AddField(
            model_name='event',
            name='sub_discipline',
            field=models.ForeignKey(help_text='Выберите субдисциплину', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sub_discipline', to='events.subdiscipline', verbose_name='Субдисциплина уличного спорта'),
        ),
        migrations.AddField(
            model_name='area',
            name='sub_discipline',
            field=models.ForeignKey(help_text='Выберите субдисциплину', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sub_discipline', to='events.subdiscipline', verbose_name='Субдисциплина уличного спорта'),
        ),
        migrations.AddConstraint(
            model_name='subdiscipline',
            constraint=models.UniqueConstraint(fields=('name', 'discipline'), name='unique_subdiscipline_name_per_discipline'),
        ),
    ]
