# Generated by Django 5.1.11 on 2025-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'площадки', 'verbose_name_plural': 'площадки'},
        ),
        migrations.AlterField(
            model_name='area',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='gallerysubdiscipline',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
