# Generated by Django 5.1.11 on 2025-07-05 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель региона'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(help_text='Выберите регион', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='regions.region', verbose_name='Регион'),
        ),
    ]
