version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - street_russia_network

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    container_name: backend
    command: gunicorn config.wsgi:application --workers 5 --threads 2 --timeout 60 --preload --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - static:/app/back_static
      - media:/app/back_media
    networks:
      - street_russia_network

  nextjs:
    build:
      context: ./new-frontend
    container_name: nextjs
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - street_russia_network

  celery:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    command: celery -A config worker --loglevel=info
    depends_on:
      - backend
      - redis
    networks:
      - street_russia_network

  redis:
    image: redis:latest
    env_file:
      - ./backend/.env
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_password
    networks:
      - street_russia_network


volumes:
  static:
  media:
  db_data:

networks:
  street_russia_network:
    external: true