version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
    container_name: backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - static:/app/back_static/
      - media:/app/back_media/

  celery:
    build:
      context: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env



  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - static:/app/back_static/
      - media:/app/back_media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend


volumes:
  static:
  media:
  db_data:
