# Generated by Django 5.1.11 on 2025-07-05 06:27

import ckeditor.fields
import common.utils
import common.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('discipline', models.PositiveIntegerField(verbose_name='Количество направлений')),
                ('regions', models.PositiveIntegerField(verbose_name='Количество регионов')),
                ('media_publications', models.PositiveIntegerField(verbose_name='Количество Публикаций в СМИ')),
                ('event', models.PositiveIntegerField(verbose_name='Количество мероприятий')),
                ('person', models.PositiveIntegerField(verbose_name='Количество членов организаций')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='ContactFooter',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на соцсеть')),
                ('image', models.ImageField(help_text='Загрузите изображение соцсети', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'контакты (footer)',
                'verbose_name_plural': 'контакты (footer)',
            },
        ),
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('youtube', models.URLField(verbose_name='Ссылка на Youtube')),
                ('telegram', models.URLField(verbose_name='Ссылка на Telegram')),
                ('vkontakte', models.URLField(verbose_name='Ссылка на VK')),
            ],
            options={
                'verbose_name': 'контакты (header)',
                'verbose_name_plural': 'контакты (header)',
            },
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текстовое описание')),
                ('partners_count', models.PositiveIntegerField(verbose_name='Количество партнеров')),
                ('projects_count', models.PositiveIntegerField(verbose_name='Количество реализованных проектов')),
            ],
            options={
                'verbose_name': 'сотрудничество',
                'verbose_name_plural': 'сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='EmailFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта поддержки в Footer')),
            ],
            options={
                'verbose_name': 'почта (footer)',
                'verbose_name_plural': 'почта (footer)',
            },
        ),
        migrations.CreateModel(
            name='EveryoneLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('title', models.CharField(help_text='Укажите здесь: Студент, Школьник, Бизнесмен', max_length=55, verbose_name='Название')),
                ('description', models.CharField(max_length=165, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'у нас понравится всем',
                'verbose_name_plural': 'у нас понравится всем',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('person', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('discipline', models.PositiveIntegerField(verbose_name='Количество дисциплин')),
                ('organization', models.PositiveIntegerField(verbose_name='Количество организаций')),
                ('event', models.PositiveIntegerField(verbose_name='Количество мероприятий')),
            ],
            options={
                'verbose_name': 'информация',
                'verbose_name_plural': 'информация',
            },
        ),
        migrations.CreateModel(
            name='JoinStreet',
            fields=[
                ('format_type', models.CharField(choices=[('video_url', 'Видео'), ('image', 'Изображение')], help_text='Выберите тип медиа (Изображение или видео)', max_length=25, verbose_name='Тип контента')),
                ('video_url', models.CharField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', max_length=1000, null=True, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текстовое описание')),
            ],
            options={
                'verbose_name': 'стань частью улицы',
                'verbose_name_plural': 'стань частью улицы',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'миссия',
                'verbose_name_plural': 'миссия',
            },
        ),
        migrations.CreateModel(
            name='MissionAndGoalsImage',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Определяет порядок отображения изображения.', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Изображение миссии и целей',
                'verbose_name_plural': 'Изображения миссии и целей',
            },
        ),
        migrations.CreateModel(
            name='MissionAndGoalsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('mission', models.CharField(help_text='Опишите миссию организации.', max_length=300, verbose_name='Миссия')),
                ('goal', models.CharField(help_text='Опишите цель организации.', max_length=300, verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Миссия и цели (текст)',
                'verbose_name_plural': 'Миссия и цели (текст)',
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('iframe', models.CharField(help_text='Введите iframe Яндекс.Карт, начинающийся с <iframe>.', max_length=1000, validators=[common.validators.validate_iframe], verbose_name='Адрес Яндекс.Карт')),
                ('address', models.CharField(max_length=65, verbose_name='Адрес')),
                ('work_time', models.CharField(max_length=55, verbose_name='Дни работы и время')),
                ('phone', models.CharField(max_length=25, validators=[common.validators.validate_phone_number], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='PromotionalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('video_url', models.CharField(help_text='Введите URL видео в формате iframe для отображения на сайте.', max_length=1000, validators=[common.validators.validate_iframe], verbose_name='Ссылка на видео (iframe)')),
            ],
            options={
                'verbose_name': 'промо-видео',
                'verbose_name_plural': 'Промо-видео',
            },
        ),
        migrations.CreateModel(
            name='StreetIsUsImage',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Определяет порядок отображения изображения.', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'улица это мы',
                'verbose_name_plural': 'улица это мы',
            },
        ),
    ]
