# Generated by Django 5.1.11 on 2025-07-07 10:56

import common.utils
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContent',
            fields=[
                ('format_type', models.CharField(choices=[('video_url', 'Видео'), ('image', 'Изображение')], help_text='Выберите тип медиа (Изображение или видео)', max_length=25, verbose_name='Тип контента')),
                ('video_url', models.CharField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', max_length=1000, null=True, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('event', 'Event'), ('area', 'Area')], help_text='Тип записи (event или area). Должен быть только один объект каждого типа.', max_length=10, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Промо блок страница мероприятия',
                'verbose_name_plural': 'Промо блок страница мероприятия',
            },
        ),
    ]
