# Generated by Django 5.1.11 on 2025-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_eventcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontent',
            name='type',
            field=models.CharField(choices=[('event', 'Мероприятия'), ('area', 'Площадки')], help_text='Тип записи (event или area). Должен быть только один объект каждого типа.', max_length=10, unique=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='eventcontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='joinstreet',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='promotionalvideo',
            name='video_url',
            field=models.URLField(help_text='URL видео', max_length=1000, verbose_name='Ссылка на видео'),
        ),
    ]
