# Generated by Django 5.1.11 on 2025-07-08 15:43

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_eventcontent_type_alter_eventcontent_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinfo',
            name='iframe',
            field=models.CharField(help_text='Введите iframe Яндекс.Карт. Конструктор карты: https://yandex.ru/map-constructor/?from=constructorapi', max_length=1000, validators=[common.validators.validate_iframe], verbose_name='Адрес Яндекс.Карт'),
        ),
    ]
