# Generated by Django 5.1.11 on 2025-07-09 16:52

import contents.models.cooperation
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_organizationinfo_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='first_image',
            field=models.ImageField(default=1, help_text='Изображение (7 партнеров в России блок)', max_length=1000, upload_to=contents.models.cooperation.Cooperation.setup_first_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperation',
            name='second_image',
            field=models.ImageField(default=1, help_text='Изображение (более 50 реализованых проектов блок)', max_length=1000, upload_to=contents.models.cooperation.Cooperation.setup_second_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
