# Generated by Django 5.1.11 on 2025-07-05 06:27

import common.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('name', models.CharField(max_length=125, verbose_name='Тип партнера')),
            ],
            options={
                'verbose_name': 'тип партнера',
                'verbose_name_plural': 'тип партнера',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название партнёра')),
                ('image', models.ImageField(help_text='Загрузите изображение', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание партёра')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на партнера')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partners', to='partners.partnertype', verbose_name='Тип партнера')),
            ],
            options={
                'verbose_name': 'партнёр',
                'verbose_name_plural': 'партнёры',
            },
        ),
    ]
