# Generated by Django 5.1.11 on 2025-07-05 13:30

import ckeditor.fields
import common.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('regions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('card_image', models.ImageField(help_text='Загрузите изображение для карточки (страница новостей)', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('count_views', models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='regions.city', verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='regions.region', verbose_name='Регион')),
                ('subdiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='events.subdiscipline', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='GalleryNew',
            fields=[
                ('format_type', models.CharField(choices=[('video_url', 'Видео'), ('image', 'Изображение')], help_text='Выберите тип медиа (Изображение или видео)', max_length=25, verbose_name='Тип контента')),
                ('video_url', models.CharField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', max_length=1000, null=True, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, help_text='Использовать как основное изображение для заставки', verbose_name='Главное фото')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='news.new', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Элементы галереи',
            },
        ),
    ]
