# Generated by Django 5.1.11 on 2025-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerynew',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео', max_length=1000, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
