# Generated by Django 5.1.11 on 2025-07-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('news', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='regions.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='new',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='regions.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='new',
            name='subdiscipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='events.subdiscipline', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='gallerynew',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='news.new', verbose_name='Новость'),
        ),
    ]
