# Generated by Django 5.1.11 on 2025-07-05 06:27

import common.utils
import common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models.user
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaManager',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название соцсети')),
                ('image', models.ImageField(help_text='Загрузите изображение соцсети', max_length=1000, upload_to=common.utils.setup_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'изображение соцсети',
                'verbose_name_plural': 'изображения соцсети',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('regional_director', 'Региональный руководитель'), ('federal_director', 'Федеральный руководитель')], default='user', max_length=55, verbose_name='Роль')),
                ('avatar', models.ImageField(blank=True, max_length=1000, null=True, upload_to=users.models.user.UserAccount.setup_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Аватарка')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[common.validators.validate_phone_number], verbose_name='Телефон')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=125, null=True, verbose_name='Адрес офиса')),
                ('status', models.BooleanField(default=False, verbose_name='Является ли членом организации?')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет имеет ли пользователь доступ к админ панели.', verbose_name='Статус персонала')),
                ('is_active', models.BooleanField(default=True, help_text='Определяет имеет ли пользователь доступ к сайту.', verbose_name='Активный')),
                ('is_superuser', models.BooleanField(default=False, help_text='Дает полный доступам к админ панели.', verbose_name='Администратор')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region', verbose_name='Регион')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='SocialLinkManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('url', models.URLField(verbose_name='Ссылка на соцсеть')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.socialmediamanager', verbose_name='Соцсеть руководителя')),
            ],
            options={
                'verbose_name': 'соцсеть руководителя',
                'verbose_name_plural': 'соцсети руководителя',
            },
        ),
    ]
