# Generated by Django 5.1.11 on 2025-07-05 06:27

import common.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('name', models.CharField(max_length=50, verbose_name='Имя отправителя')),
                ('content', models.TextField(verbose_name='Содержимое письма')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[common.validators.validate_phone_number], verbose_name='Номер телефона отправителя')),
                ('consent_to_rights', models.BooleanField(verbose_name='Согласие с правилами')),
                ('consent_to_processing', models.BooleanField(verbose_name='Согласие на обработку данных')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('CLOSED', 'Закрыто')], default='PENDING', max_length=50, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('text', models.TextField(verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Ответ на заявку',
                'verbose_name_plural': 'Ответы на заявки',
            },
        ),
    ]
