# Generated by Django 5.1.11 on 2025-07-06 15:40

import common.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0003_alter_city_name_alter_region_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('name', models.CharField(max_length=50, verbose_name='Имя отправителя')),
                ('phone', models.CharField(max_length=12, validators=[common.validators.validate_phone_number], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('CLOSED', 'Закрыто')], default='PENDING', max_length=50, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='FeedbackOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('gender', models.CharField(max_length=25, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=12, validators=[common.validators.validate_phone_number], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('social', models.CharField(max_length=125, verbose_name='Соцсеть для связи')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('passport_issuer', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('CLOSED', 'Закрыто')], default='PENDING', max_length=50, verbose_name='Статус заявки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_organizations', to='regions.city', verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_organizations', to='regions.region', verbose_name='Регион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
