# Generated by Django 5.1.11 on 2025-07-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackorganization',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_organizations', to='regions.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='feedbackorganization',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_organizations', to='regions.region', verbose_name='Регион'),
        ),
    ]
